compiler:
  solc:
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.6.0/contracts"
      - "@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.6.0/contracts"
networks:
  default: development

networks:
  default: hardhat-fork
  hardhat-fork:
    cmd_settings:
      fork_block: 16350543
  
reports:
  exclude_paths:
    - interfaces/**/*.*

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.6.0
